name: manager-terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
  TF_VERSION: 1.15.8
  TF_VAR_github_owner: ${{ github.repository_owner }}
  TF_VAR_app_id: ${{ vars.IAC_GITHUB_APP_ID }}
  TF_VAR_app_installation_id: ${{ vars.IAC_GITHUB_APP_INSTALLATION_ID }}
  TF_VAR_app_pem_file: ${{ secrets.IAC_GIHUB_APP_PEM }}

defaults:
  run:
    working-directory: first-iac-managed-repo/terraform

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: ./.github/actions
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Check Terraform formatting
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Validate Terraform configuration
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'


